"""Added theme table

Revision ID: 9f34d3373d63
Revises: 
Create Date: 2025-11-21 20:13:08.671636

"""
import os
import sys
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Add your project root to the Python path
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))))

from jeoparty.api.config import Config
from jeoparty.api.enums import Language
from jeoparty.api.orm.models import Theme


# revision identifiers, used by Alembic.
revision: str = '9f34d3373d63'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('power_ups')
    with op.batch_alter_table("contestants") as batch_op:
        batch_op.alter_column('name',
            existing_type=sa.VARCHAR(length=32),
            type_=sa.String(length=16),
            existing_nullable=False)

    with op.batch_alter_table("game_power_ups") as batch_op:
        batch_op.drop_constraint("power_id", type_='foreignkey')

    op.drop_column('game_power_ups', 'power_id')

    with op.batch_alter_table("games") as batch_op:
        batch_op.alter_column('title',
                existing_type=sa.VARCHAR(length=64),
                type_=sa.String(length=32),
                existing_nullable=False)
        batch_op.alter_column('answer_time',
                existing_type=sa.INTEGER(),
                nullable=False)
        batch_op.alter_column('password',
                existing_type=sa.VARCHAR(length=128),
                type_=sa.String(length=64),
                existing_nullable=True)

    with op.batch_alter_table("question_categories") as batch_op:
        batch_op.alter_column('buzz_time',
                existing_type=sa.INTEGER(),
                nullable=True)

    op.add_column('question_packs', sa.Column('theme_id', sa.String(length=64), nullable=True))

    with op.batch_alter_table("question_packs") as batch_op:
        batch_op.alter_column('language',
                existing_type=sa.VARCHAR(length=7),
                nullable=False)
        batch_op.alter_column('lobby_music',
                existing_type=sa.NVARCHAR(length=64),
                type_=sa.String(length=128),
                existing_nullable=True)
        batch_op.alter_column('lobby_volume',
                existing_type=sa.REAL(),
                type_=sa.Float(),
                existing_nullable=True)
        batch_op.create_foreign_key("theme_id", 'themes', ['theme_id'], ['id'])
        batch_op.create_foreign_key("created_by", 'users', ['created_by'], ['id'])

    with op.batch_alter_table("games") as batch_op:
        batch_op.create_foreign_key("created_by", 'users', ['created_by'], ['id'])

    op.drop_column('question_packs', 'theme')
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question_packs', sa.Column('theme', sa.NVARCHAR(length=64), nullable=True))
    op.drop_constraint(None, 'question_packs', type_='foreignkey')
    op.drop_constraint(None, 'question_packs', type_='foreignkey')
    op.alter_column('question_packs', 'lobby_volume',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('question_packs', 'lobby_music',
               existing_type=sa.String(length=128),
               type_=sa.NVARCHAR(length=64),
               existing_nullable=True)
    op.alter_column('question_packs', 'language',
               existing_type=sa.VARCHAR(length=7),
               nullable=True)
    op.drop_column('question_packs', 'theme_id')
    op.alter_column('question_categories', 'buzz_time',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('games', 'password',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)
    op.alter_column('games', 'answer_time',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('games', 'title',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
    op.add_column('game_power_ups', sa.Column('power_id', sa.VARCHAR(length=128), nullable=False))
    op.create_foreign_key(None, 'game_power_ups', 'power_ups', ['power_id'], ['id'])
    op.alter_column('contestants', 'name',
               existing_type=sa.String(length=16),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    op.add_column('buzzer_sounds', sa.Column('pack_id', sa.VARCHAR(length=64), nullable=False))
    op.drop_constraint(None, 'buzzer_sounds', type_='foreignkey')
    op.create_foreign_key(None, 'buzzer_sounds', 'question_packs', ['pack_id'], ['id'])
    op.drop_column('buzzer_sounds', 'theme_id')
    op.create_table('power_ups',
    sa.Column('id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('pack_id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('type', sa.VARCHAR(length=6), nullable=False),
    sa.Column('icon', sa.VARCHAR(length=128), nullable=True),
    sa.Column('video', sa.VARCHAR(length=128), nullable=True),
    sa.ForeignKeyConstraint(['pack_id'], ['question_packs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###